import imageDracoMalfoyWand from './Harry-Potter-Draco-Malfoys-Wand.png'
import imageDumbledoreWand from './Harry-Potter-Dumbledore-Wand.png'
import imageGellertGrindewaldWand from './Harry-Potter-Gellert-Grindelwald-Wand.png'
import imageHermioneGrangersWand from './Harry-Potter-Hermione-Grangers-Wand.png'
import imageLordVoldemortsWand from './Harry-Potter-Lord-Voldemorts-Wand.png'
import imageNicolasFlamelWand from './Harry-Potter-Nicolas-Flamel-Wand.png'
import imageProfessorSnapeWand from './Harry-Potter-Professor-Snape-Wand.png'
import imageRonWeasleysWand from './Harry-Potter-Ron-Weasleys-Wand.png'
import imageSiriusBlackWand from './Harry-Potter-Sirius-Black-Wand.png'
import imageOllivandersWand from './Harry-Potter-Wand-with-Ollivanders-Wand.png'

export const products = [
  {
    image: imageNicolasFlamelWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Nicolas Flamel Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageGellertGrindewaldWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Nicolas Flamel Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageDumbledoreWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Dumbledore Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageSiriusBlackWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Sirius Black Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageHermioneGrangersWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Hermione Granger's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageDracoMalfoyWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Draco Malfoy's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageRonWeasleysWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Ron Weasley's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageLordVoldemortsWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Lord Voldemort's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageProfessorSnapeWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Professor Snape Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageOllivandersWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Wand with Ollivanders Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageLordVoldemortsWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Lord Voldemort's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageProfessorSnapeWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Professor Snape Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageOllivandersWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Wand with Ollivanders Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageSiriusBlackWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Sirius Black Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageHermioneGrangersWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Hermione Granger's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageDracoMalfoyWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Draco Malfoy's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageNicolasFlamelWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Nicolas Flamel Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageGellertGrindewaldWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Nicolas Flamel Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageDumbledoreWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Dumbledore Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageSiriusBlackWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Sirius Black Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageHermioneGrangersWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Hermione Granger's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageDracoMalfoyWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Draco Malfoy's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageRonWeasleysWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Ron Weasley's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageLordVoldemortsWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Lord Voldemort's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageProfessorSnapeWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Professor Snape Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageOllivandersWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Wand with Ollivanders Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageLordVoldemortsWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Lord Voldemort's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageProfessorSnapeWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Professor Snape Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageOllivandersWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Wand with Ollivanders Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageSiriusBlackWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: 'Harry Potter Sirius Black Wand',
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageHermioneGrangersWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Hermione Granger's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
  {
    image: imageDracoMalfoyWand,
    currentCost: '$46.00',
    originCost: '$64.00',
    shop: 'Ollivanders',
    shopLink: '',
    productName: "Harry Potter Draco Malfoy's Wand",
    overallRating: 4,
    reviews: 1337,
    sales: -33,
    freeShipping: true,
  },
]